name: Build, Test, and Publish Docker Image

on:
  push:
    branches: [main] # Adjust branches as needed
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository so that the workflow can access your code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx for advanced build features (including multi-platform support).
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry.
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build the Docker image using your Dockerfile and push it.
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/zeppelin-backend:latest
            ghcr.io/${{ github.repository_owner }}/zeppelin-backend:${{ github.sha }}
